### ISSUE TITLE
V3 Tracking Issue

### ISSUE THREAD

**Issue by Vehmloewff** [Vehmloewff/deno-utils#5]
**Features**

- [x] Cache utils
- [x] Json overhaul; add `SafeUnkown`; remove json verifiers
- [x] Cbor
- [ ] Test coverage
- [ ] Stabilize deno module
  - [ ] Add `bench`
  - [ ] Add `run`
  - [ ] Add `--coverage` to test
- [ ] Stabilize record module
- [ ] Testing utils
  - [ ] `TestServer`
- [ ] Number module
  - [ ] `formatLargeNumber`
- [ ] `logger` and `console` interceptor and throttle
- [ ] Find a good place for, and include `download` and `unzip` and other such things

**Refactors**

- [ ] Add coverage reports to our own tests
- [ ] Put doc and module comments (mostly) everywhere

**At Release**

- [ ] Switch FS read return types to be `T | null`
